#!/bin/bash
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --job-name=container-gpu
#SBATCH --output=job.%j.out
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu
#SBATCH --time=10:00:00
#SBATCH --partition=acltr

module load Apptainer       # or Singularity module
export HUGGINGFACE_HUB_TOKEN=

# bind your code directory into the container and run
/home/jnah/appcontainer-install/bin/appcontainer exec \
  --bind $PWD:/mnt/host \
  myenv.sif \
  python models/baseline.py

